# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../src/SmartBuilding/main/SmartBuilding.h \
    ../../src/SmartBuilding/main/topBar/topBar.h \
    ../../src/SmartBuilding/main/topBar/topBarEvent.h \
    ../../src/SmartBuilding/main/content/contentMgr.h \
    ../../src/SmartBuilding/main/content/menuBar/menuBar.h \
    ../../src/SmartBuilding/main/content/funWidget/config/colorWidget.h \
    ../../src/SmartBuilding/main/content/funWidget/config/configWidget.h \
    ../../src/SmartBuilding/main/content/funWidget/config/dimTableWidget.h \
    ../../src/SmartBuilding/main/content/funWidget/config/disposeWidget.h \
    ../../src/SmartBuilding/main/content/funWidget/system/baseSetWidget.h \
    ../../src/SmartBuilding/main/content/funWidget/system/defendWidget.h \
    ../../src/SmartBuilding/main/content/funWidget/system/pwdWidget.h \
    ../../src/SmartBuilding/main/content/funWidget/system/systemWidget.h \
    ../../src/SmartBuilding/main/content/funWidget/log/blackBoxWidget.h \
    ../../src/SmartBuilding/main/content/funWidget/log/logContent.h \
    ../../src/SmartBuilding/main/content/funWidget/log/logWidget.h \
    ../../src/SmartBuilding/main/content/funWidget/log/recordWidget.h \
    ../../src/SmartBuilding/main/content/funWidget/timeCtrl/circuitSelection.h \
    ../../src/SmartBuilding/main/content/funWidget/timeCtrl/timeCtrlWidget.h \
    ../../src/SmartBuilding/main/content/funWidget/timeCtrl/timeTask.h \
    ../../src/SmartBuilding/main/content/funWidget/timeCtrl/timeTaskInfoW.h \
    ../../src/SmartBuilding/main/content/funWidget/timeCtrl/timeTaskOrder.h \
    ../../src/SmartBuilding/main/content/funWidget/lightCtrl/lightCtrlWidget.h \
    ../../src/SmartBuilding/main/content/funWidget/lightCtrl/lightTask.h \
    ../../src/SmartBuilding/main/content/funWidget/lightCtrl/lightTaskInfoW.h \
    ../../src/SmartBuilding/main/content/funWidget/lightCtrl/lightTaskOrder.h \
    ../../src/SmartBuilding/main/content/funWidget/lightCtrl/sensorSelectionW.h \
    ../../src/SmartBuilding/main/content/funWidget/constanceAs/constanceAsTask.h \
    ../../src/SmartBuilding/main/content/funWidget/constanceAs/constanceAsWidget.h \
    ../../src/SmartBuilding/main/content/funWidget/constanceAs/execTimeWidget.h \
    ../../src/SmartBuilding/main/content/funWidget/constanceAs/weightWidget.h \
    ../../src/SmartBuilding/main/content/funWidget/monitor/monitorWidget.h \
    ../../src/SmartBuilding/dataLevel/baseDevice.h \
    ../../src/SmartBuilding/dataLevel/cabinet.h \
    ../../src/SmartBuilding/dataLevel/circuit.h \
    ../../src/SmartBuilding/dataLevel/database.h \
    ../../src/SmartBuilding/dataLevel/dataMgr.h \
    ../../src/SmartBuilding/dataLevel/rectifier.h \
    ../../src/SmartBuilding/dataLevel/dataComm/base/FileBase.h \
    ../../src/SmartBuilding/dataLevel/dataComm/sharemem/ipcSharemem.h \
    ../../src/SmartBuilding/dataLevel/dataComm/sharemem/ipcStatus.h \
    ../../src/SmartBuilding/dataLevel/dataComm/sharemem/sharemem.h \
    ../../src/SmartBuilding/dataLevel/dataComm/include/stdinclude.h \
    ../../src/SmartBuilding/dataLevel/dataComm/include/type.h \
    ../../src/SmartBuilding/dataLevel/dataComm/include/typedef.h \
    ../../src/SmartBuilding/main/content/common_ctl/baseOrderWidget.h \
    ../../src/SmartBuilding/main/content/common_ctl/baseTask.h \
    ../../src/SmartBuilding/main/content/common_ctl/comboBoxDelegate.h \
    ../../src/SmartBuilding/main/content/common_ctl/lineEditDelegate.h \
    ../../src/SmartBuilding/main/content/common_ctl/lineEditRealDelegate.h \
    ../../src/SmartBuilding/main/content/common_ctl/logReportWidget.h \
    ../../src/SmartBuilding/main/content/common_ctl/missionWidget.h \
    ../../src/SmartBuilding/main/content/common_ctl/nofocusItemdelegate.h \
    ../../src/SmartBuilding/main/content/common_ctl/popInputPwd.h \
    ../../src/SmartBuilding/main/content/common_ctl/popSureWidget.h \
    ../../src/SmartBuilding/main/content/common_ctl/reportView.h \
    ../../src/SmartBuilding/main/content/common_ctl/reportWidget.h \
    ../../src/SmartBuilding/main/content/common_ctl/sqlTableModel.h \
    ../../src/SmartBuilding/main/content/common_ctl/taskBaseInfoW.h \
    ../../src/SmartBuilding/main/content/common_ctl/weekSelection.h \
    ../../src/SmartBuilding/main/content/common_ctl/application.h
SOURCES += ../../src/SmartBuilding/main/main.cpp \
    ../../src/SmartBuilding/main/SmartBuilding.cpp \
    ../../src/SmartBuilding/main/topBar/topBar.cpp \
    ../../src/SmartBuilding/main/content/contentMgr.cpp \
    ../../src/SmartBuilding/main/content/menuBar/menuBar.cpp \
    ../../src/SmartBuilding/main/content/funWidget/config/colorWidget.cpp \
    ../../src/SmartBuilding/main/content/funWidget/config/configWidget.cpp \
    ../../src/SmartBuilding/main/content/funWidget/config/dimTableWidget.cpp \
    ../../src/SmartBuilding/main/content/funWidget/config/disposeWidget.cpp \
    ../../src/SmartBuilding/main/content/funWidget/system/baseSetWidget.cpp \
    ../../src/SmartBuilding/main/content/funWidget/system/defendWidget.cpp \
    ../../src/SmartBuilding/main/content/funWidget/system/pwdWidget.cpp \
    ../../src/SmartBuilding/main/content/funWidget/system/systemWidget.cpp \
    ../../src/SmartBuilding/main/content/funWidget/log/blackBoxWidget.cpp \
    ../../src/SmartBuilding/main/content/funWidget/log/logContent.cpp \
    ../../src/SmartBuilding/main/content/funWidget/log/logWidget.cpp \
    ../../src/SmartBuilding/main/content/funWidget/log/recordWidget.cpp \
    ../../src/SmartBuilding/main/content/funWidget/timeCtrl/circuitSelection.cpp \
    ../../src/SmartBuilding/main/content/funWidget/timeCtrl/timeCtrlWidget.cpp \
    ../../src/SmartBuilding/main/content/funWidget/timeCtrl/timeTask.cpp \
    ../../src/SmartBuilding/main/content/funWidget/timeCtrl/timeTaskInfoW.cpp \
    ../../src/SmartBuilding/main/content/funWidget/timeCtrl/timeTaskOrder.cpp \
    ../../src/SmartBuilding/main/content/funWidget/lightCtrl/lightCtrlWidget.cpp \
    ../../src/SmartBuilding/main/content/funWidget/lightCtrl/lightTask.cpp \
    ../../src/SmartBuilding/main/content/funWidget/lightCtrl/lightTaskInfoW.cpp \
    ../../src/SmartBuilding/main/content/funWidget/lightCtrl/lightTaskOrder.cpp \
    ../../src/SmartBuilding/main/content/funWidget/lightCtrl/sensorSelectionW.cpp \
    ../../src/SmartBuilding/main/content/funWidget/constanceAs/constanceAsTask.cpp \
    ../../src/SmartBuilding/main/content/funWidget/constanceAs/constanceAsWidget.cpp \
    ../../src/SmartBuilding/main/content/funWidget/constanceAs/execTimeWidget.cpp \
    ../../src/SmartBuilding/main/content/funWidget/constanceAs/weightWidget.cpp \
    ../../src/SmartBuilding/main/content/funWidget/monitor/monitorWidget.cpp \
    ../../src/SmartBuilding/dataLevel/baseDevice.cpp \
    ../../src/SmartBuilding/dataLevel/cabinet.cpp \
    ../../src/SmartBuilding/dataLevel/circuit.cpp \
    ../../src/SmartBuilding/dataLevel/dataMgr.cpp \
    ../../src/SmartBuilding/dataLevel/rectifier.cpp \
    ../../src/SmartBuilding/dataLevel/dataComm/base/FileBase.cpp \
    ../../src/SmartBuilding/dataLevel/dataComm/sharemem/ipcSharemem.cpp \
    ../../src/SmartBuilding/dataLevel/dataComm/sharemem/ipcStatus.cpp \
    ../../src/SmartBuilding/dataLevel/dataComm/sharemem/sharemem.cpp \
    ../../src/SmartBuilding/main/content/common_ctl/baseOrderWidget.cpp \
    ../../src/SmartBuilding/main/content/common_ctl/baseTask.cpp \
    ../../src/SmartBuilding/main/content/common_ctl/comboBoxDelegate.cpp \
    ../../src/SmartBuilding/main/content/common_ctl/lineEditDelegate.cpp \
    ../../src/SmartBuilding/main/content/common_ctl/lineEditRealDelegate.cpp \
    ../../src/SmartBuilding/main/content/common_ctl/logReportWidget.cpp \
    ../../src/SmartBuilding/main/content/common_ctl/missionWidget.cpp \
    ../../src/SmartBuilding/main/content/common_ctl/nofocusItemdelegate.cpp \
    ../../src/SmartBuilding/main/content/common_ctl/reportView.cpp \
    ../../src/SmartBuilding/main/content/common_ctl/reportWidget.cpp \
    ../../src/SmartBuilding/main/content/common_ctl/sqlTableModel.cpp \
    ../../src/SmartBuilding/main/content/common_ctl/taskBaseInfoW.cpp \
    ../../src/SmartBuilding/main/content/common_ctl/weekSelection.cpp \
    ../../src/SmartBuilding/main/content/common_ctl/application.cpp
FORMS += ../../src/SmartBuilding/main/SmartBuilding.ui
RESOURCES += ./SmartBuilding.qrc
